### ISSUE TITLE
Java version error on latest build (v2.37.0)

### ISSUE THREAD

**Issue by sternschnaube** [Minecraft-AMS/Carpet-AMS-Addition#100]
### Bug description

![image](https://github.com/Minecraft-AMS/Carpet-AMS-Addition/assets/120551916/9779d867-4ca0-4e51-a83b-26382bc3c5e3)

### Steps to reproduce

/

### Minecraft version

1.20.4

### TemplateMod version

v2.37.0

### Check list

- [X] I have verified that the issue persists in the latest version of the mod.
- [X] I have searched the existing issues and confirmed that this is not a duplicate.

**Comment by 1024-byteeeee** [comment]
I've noticed this issue. Before the next version update, you can use v2.37.0 by installing Java 21.

**Comment by 1024-byteeeee** [comment]
### Changelog
#### https://minecraft-ams.github.io/carpetamsaddition/2024/04/10/v2.38.0/
### GitHub
#### https://github.com/Minecraft-AMS/Carpet-AMS-Addition/releases/tag/v2.38.0
### Modrinth
#### https://modrinth.com/mod/carpet-ams-addition/versions

**Comment by sternschnaube** [comment]
Thank you - new version works great 😊
