### ISSUE TITLE
easyGetPitcherPod 规则在 1.20.1 版本注入失败，导致无法启动游戏

### ISSUE THREAD

**Issue by LittleCircleOO** [Minecraft-AMS/Carpet-AMS-Addition#101]
### Bug description

在 1.20.1 版本，仅安装 Fabric-Loader (0.15.10)、Fabric-Api (0.92.1)、Carpet (1.4.112+v230608) 与本模组 (2.38.0~2.38.1) 的情况下，无法启动游戏，提示 easyGetPitcherPod 规则的相关代码注入失败（详见日志）。

### Steps to reproduce

1. 在 1.20.1 版本安装 Fabric-Loader (0.15.10)、Fabric-Api (0.92.1)、Carpet (1.4.112+v230608) 与本模组 (2.38.0~2.38.1)；
2. 尝试运行游戏；
3. 游戏崩溃。

### Expected behavior

正常启动游戏。

### Actual behavior

游戏崩溃，详见日志。

### Relevant logs

https://mclo.gs/74eflVW

### Minecraft version

1.20.1

### TemplateMod version

影响范围 2.38.0~2.38.1（该问题在最新版仍未修复）

### Other information

相关模组文件：

* fabric-api-0.92.1+1.20.1.jar
* fabric-carpet-1.20-1.4.112+v230608.jar
* Carpet-AMS-Addition-mc1.20.1-fabric-v2.38.1.jar

### Check list

- [X] I have verified that the issue persists in the latest version of the mod.
- [X] I have searched the existing issues and confirmed that this is not a duplicate.

**Comment by 1024-byteeeee** [comment]
下个版本修复。
