### ISSUE TITLE
Crash on client

### ISSUE THREAD

**Issue by sternschnaube** [Minecraft-AMS/Carpet-AMS-Addition#104]
### Bug description

https://pastebin.com/raw/YDaJ8GAA

### Steps to reproduce

/

### Minecraft version

1.20.6

### TemplateMod version

v2.44.0

### Check list

- [X] I have verified that the issue persists in the latest version of the mod.
- [X] I have searched the existing issues and confirmed that this is not a duplicate.

**Comment by 1024-byteeeee** [comment]
https://github.com/Minecraft-AMS/Carpet-AMS-Addition/releases/tag/v2.44.1

**Comment by sternschnaube** [comment]
Thanks!!
