### ISSUE TITLE
重构了合成表API，可能需要进一步调整

### ISSUE THREAD

**Issue by 1024-byteeeee** [Minecraft-AMS/Carpet-AMS-Addition#106]
需要一种新的方式来在carpet中实现可开关的合成配方，而不是使用数据包。

**Comment by 1024-byteeeee** [comment]
@wendavid552 提供了一种可能的解决办法：
https://beatseat.github.io/2024/06/13/ams-plan/

**Comment by 1024-byteeeee** [comment]
在Carpet AMS Addition v2.44.6中临时处理了与Minecraft 1.21的兼容性。

**Comment by 1024-byteeeee** [comment]
先摆

**Comment by cdqtzrc** [comment]
> 先摆

那我也摆

**Comment by wendavid552** [comment]
要不我们直接给recipeManager里面inject进去吧
