### ISSUE TITLE
[功能请求]添加规则，在1.20.2+版本中回滚MC-181190修复，使得交易折扣可叠加

### ISSUE THREAD

**Issue by LittleCircleOO** [Minecraft-AMS/Carpet-AMS-Addition#107]
### Motivation

针对 MC-181190 的修复回退，虽然有几个 mod 实现了此功能，但多为独立的 mod，添加即生效，规则无法热切换，且仅发布一个版本就不再更新。
希望能作为本 mod 的一条规则实现该特性。

### Description

stackableDiscount 规则
回滚 23w31a 中 mojang 对 MC-181190 的修复，使村民交易折扣可通过反复治愈实现叠加。

### Other information

可参考相关实现：
https://github.com/asablock/unfixmc181190/blob/master/src/main/java/io/github/asablock/unfixmc181190/MixinVillageGossipType.java
https://github.com/Sindercube/Discount-Stacking-Fix/blob/main/src/main/java/com/sindercube/dsf/mixin/VillagerMixin.java
https://github.com/No-Eul/rscd/blob/master/src/main/java/dev/noeul/fabricmod/rscd/mixin/VillageGossipTypeMixin.java

**Comment by 1024-byteeeee** [comment]
目前在开发别的项目，要等一段时间。

**Comment by wendavid552** [comment]
好的，我会在后续版本中添加相关规则。

**Comment by 1024-byteeeee** [comment]
# Carpet-AMS-Addition v2.45.0
### Changelog
#### https://minecraft-ams.github.io/carpetamsaddition/2024/07/18/v2.45.0/

### Github
#### https://github.com/Minecraft-AMS/Carpet-AMS-Addition/releases/tag/v2.45.0

### Modrinth
#### https://modrinth.com/mod/carpet-ams-addition/versions

### CurseForge
#### https://www.curseforge.com/minecraft/mc-mods/carpet-ams-addition
