### ISSUE TITLE
ShulkerBoxBlockEntityMixin - Set INVENTORY_SIZE

### ISSUE THREAD

**Issue by BVengo** [Minecraft-AMS/Carpet-AMS-Addition#110]
### Motivation

I would like easier compatibility with other mods, without them needing to have their own accessors that need to work around this mod.

### Description

This mod has the feature to increase the size of shulkers. In doing so, it needs the mixin ShulkerBoxBlockEntityMixin to modify various functions and sizes. The base class `ShulkerBoxBlockEntity` has a public constant called `INVENTORY_SIZE` that isn't being set by the mod. I would like to see it set to whatever the current configs allow.

### Other information

I'm requesting this because of an issue opened for my own mod Simple Shulker Preview: [Issue here](https://github.com/BVengo/simple-shulker-preview/issues/33).

I'm working with ItemStack objects rather than ShulkerBoxBlockEntity objects, so cannot directly use the `size()` function that is modified by your mod. Instead, I rely on the `public static final int INVENTORY_SIZE;`

**Comment by wendavid552** [comment]
Sorry that we have neglected it (That constant is from 1.19.4+ but our main project version is 1.18.2).

**However this modification could not solve the issue.** Our mod is **serverside**.

**Comment by 1024-byteeeee** [comment]
# Carpet-AMS-Addition v2.45.0
### Changelog
#### https://minecraft-ams.github.io/carpetamsaddition/2024/07/18/v2.45.0/

### Github
#### https://github.com/Minecraft-AMS/Carpet-AMS-Addition/releases/tag/v2.45.0

### Modrinth
#### https://modrinth.com/mod/carpet-ams-addition/versions

### CurseForge
#### https://www.curseforge.com/minecraft/mc-mods/carpet-ams-addition
