### ISSUE TITLE
[需求] - 拴绳防断

### ISSUE THREAD

**Issue by Adogs1** [Minecraft-AMS/Carpet-AMS-Addition#120]
### Motivation

在1.21中，玩家可以用拴绳牵引承载了实体的船，以此可以使用鞘翅飞行快速运输实体。请添加规则使拴绳永不会断，以保证我可以运输实体时不用担心因为操作不当导致拴绳断开

### Description

如上

**Comment by wendavid552** [comment]
难倒不难，只是有点担心会不会有奇怪的区块加载相关的bug（）

**Comment by Adogs1** [comment]
> 难倒不难，只是有点担心会不会有奇怪的区块加载相关的bug（）

啊？还会牵扯到区块加载相关的吗？

**Comment by 1024-byteeeee** [comment]
> > 难倒不难，只是有点担心会不会有奇怪的区块加载相关的bug（）
> 
> 啊？还会牵扯到区块加载相关的吗？

uh, 大概需要实现后进行一些测试，目前的开发重心不在增加新的规则上，需要等待一段时间😊。

**Comment by Adogs1** [comment]
> > > 难倒不难，只是有点担心会不会有奇怪的区块加载相关的bug（）
> > 
> > 
> > 啊？还会牵扯到区块加载相关的吗？
> 
> uh, 大概需要实现后进行一些测试，目前的开发重心不在增加新的规则上，需要等待一段时间😊。

我将一直期待并准备更新AMS！

**Comment by 1024-byteeeee** [comment]
在此之前可以保持issue开启。

**Comment by 1024-byteeeee** [comment]
# Carpet AMS Addition v2.46.0
### Changelog
#### https://minecraft-ams.github.io/carpetamsaddition/2024/09/09/v2.46.0/

**Comment by Adogs1** [comment]
> # 地毯 AMS 添加 v2.46.0
> ### 更改日志
> #### https://minecraft-ams.github.io/carpetamsaddition/2024/09/09/v2.46.0/

感谢开发者们的付出~！！
