### ISSUE TITLE
村民获得职业无冷却

### ISSUE THREAD

**Issue by skycray599944** [Minecraft-AMS/Carpet-AMS-Addition#128]
### Motivation

我希望在刷附魔书的时候可以快点

### Description

我希望村民只要离得够近，就可以在我放下职业方块一瞬间获得职业

**Comment by wendavid552** [comment]
这个功能可以加，但是加进去之后可能会让普通村民（没有绑定职业方块的村民）变卡很多（可能比原来多几倍卡顿），因为这相当于频繁寻路

**Comment by 1024-byteeeee** [comment]
### Changelog
####https://minecraft-ams.github.io/carpetamsaddition/2024/09/21/v2.48.0/

### 轻松刷新交易（easyRefreshTrades）
当村民之前没有与玩家达成过交易时，每次打开交易界面都会刷新村民出售的内容。

你可以使用这条规则满足你的需求。
