### ISSUE TITLE
1.20.1、1.20.4版本的伪和平功能，开启后仍然会刷出溺尸。

### ISSUE THREAD

**Issue by Goat-elegant** [Minecraft-AMS/Carpet-AMS-Addition#133]
### Bug description

1.20.1、1.20.4版本的伪和平功能（在生存时遇到的，仅使用了这两个版本），开启后仍然会刷出溺尸。
具体版本：
Carpet-AMS-Addition-mc1.20.1-fabric-v2.44.6.jar
Carpet-AMS-Addition-mc1.20.4-fabric-v2.45.2.jar

### Steps to reproduce

功能开启后在能刷出溺尸的群系都会生成。

### Minecraft version

1.20.1 1.20.4

### TemplateMod version

Carpet-AMS-Addition-mc1.20.1-fabric-v2.44.6.jar、Carpet-AMS-Addition-mc1.20.4-fabric-v2.45.2.jar

### Check list

- [ ] I have verified that the issue persists in the latest version of the mod.
- [ ] I have searched the existing issues and confirmed that this is not a duplicate.

**Comment by wendavid552** [comment]
模组之前的伪和平实现与通用的伪和平原理有差别，除溺尸外恐怕守卫者等也会生成。

将在下次release前解决。

**Comment by wendavid552** [comment]
考虑到其实这个功能的目的应该和`doMobSpawning`差不多，所以我们干脆改成相当于填充其中某种怪物上限（例如，仅怪物的伪和平，仅动物的伪和平，仅发光鱿鱼的伪和平）

**Comment by Goat-elegant** [comment]
在1.20.4版本，服务器内开启伪和平功能，在红树林沼泽，青蛙似乎也不能刷出来，取消规则后，再重启服务器，就能正常刷出了。

**Comment by vocaloidkiss** [comment]
是否可以设置单独维度的伪和平？ @wendavid552

**Comment by vocaloidkiss** [comment]
作为布尔值选择

**Comment by wendavid552** [comment]
> 是否可以设置单独维度的伪和平？ @wendavid552

说得对，将考虑在下个版本添加。

**Comment by Goat-elegant** [comment]
又发现一个小问题，1.20.4，开启后，守卫者不受影响，还是会正常刷新。

**Comment by 1024-byteeeee** [comment]
# Carpet AMS Addition v2.46.0
### Changelog
#### https://minecraft-ams.github.io/carpetamsaddition/2024/09/09/v2.46.0/
