### ISSUE TITLE
自定义可移动方块出错

### ISSUE THREAD

**Issue by specialTT** [Minecraft-AMS/Carpet-AMS-Addition#139]
### Bug description

自定义可移动方块规则启用时，如果将列表里加入容器，容器推动时里面的东西会爆出来。

### Steps to reproduce

1.将自定义可移动方块规则加入容器方块，比如：箱子。
2.把物品装入箱子里
3.用活塞推动它

### Expected behavior

箱子连同内容物一并推拉

### Actual behavior

箱子在推动出去的那一刻把所有内容物都吐出来

### Minecraft version

1.21

### TemplateMod version

2.45.1

### Other information

其实可以直接使用地毯模组的容器推动，但是它有Bug，所以我选用了这个规则。

### Check list

- [X] I have verified that the issue persists in the latest version of the mod.
- [X] I have searched the existing issues and confirmed that this is not a duplicate.

**Comment by 1024-byteeeee** [comment]
在下个版本中，我将会让该规则不支持容器类方块，如果你需要推动容器，可以使用Carpet本体内的movableBlockEntities规则。

**Comment by 1024-byteeeee** [comment]
# Carpet AMS Addition v2.46.0
### Changelog
#### https://minecraft-ams.github.io/carpetamsaddition/2024/09/09/v2.46.0/

**Comment by specialTT** [comment]
6啊，直接解決問題根源

**Comment by 1024-byteeeee** [comment]
> 6啊，直接解決問題根源

哈哈😂

**Comment by 1024-byteeeee** [comment]
要推容器用carpet自带的吧
