### ISSUE TITLE
恢复线的特性

### ISSUE THREAD

**Issue by Adogs1** [Minecraft-AMS/Carpet-AMS-Addition#140]
### Motivation

mojang在24w33a和24w36a分别修复了剪刀可以剪除常亮绊线和破坏绊线，绊线不会消失并刷出一个线的特性，我请求把线的这些性质恢复到1.21及以前

### Description

如上

**Comment by Adogs1** [comment]
> ### 赋予动机
> mojang在24w33a和24w36a分别修复了剪刀可以剪除常亮绊线和破坏绊线，绊线不会消失并刷出一个线的特性，我请求把线的这些性质恢复到1.21及以前
> 
> ### 描述
> 如上
> 
> ### 其他信息
> _无响应_

因为这可能对空岛不是很友好？

**Comment by 1024-byteeeee** [comment]
暂时不会考虑去实现它，起码等到正式版之后。
