### ISSUE TITLE
变色羊可随机产出任意颜色羊毛

### ISSUE THREAD

**Issue by LAGANXIANG** [Minecraft-AMS/Carpet-AMS-Addition#143]
### Motivation

当一只羊命名为Jab_时羊会变成变色羊,但羊毛仍是之前未变的颜色，开启功能后，羊毛将随机掉落不同颜色的羊毛。

### Description

如上

**Comment by LAGANXIANG** [comment]
指的是剪刀剪的不是砍死的

**Comment by 1024-byteeeee** [comment]
### Changelog
#### https://minecraft-ams.github.io/carpetamsaddition/2024/09/30/v2.49.0/
