### ISSUE TITLE
更懂事的末影人

### ISSUE THREAD

**Issue by beijuren** [Minecraft-AMS/Carpet-AMS-Addition#150]
### Bug description

描述中末影人只会捡起西瓜南瓜，但是开启后末影人似乎只会捡起西瓜，无法捡起南瓜

### Steps to reproduce

1.开启更懂事的末影人
2.在末地放西瓜以及南瓜，提高tick
3.末影人只会捡起西瓜

### Expected behavior

应捡起西瓜及南瓜

### Actual behavior

只捡起了西瓜

### Minecraft version

1.21.1

### TemplateMod version

Carpet-AMS-Addition-mc1.21.1-fabric-v2.50.0.jar

### Other information

无

### Check list

- [X] I have verified that the issue persists in the latest version of the mod.
- [X] I have searched the existing issues and confirmed that this is not a duplicate.

**Comment by 1024-byteeeee** [comment]
我的问题，代码写成南瓜头了，有时间修。

**Comment by 1024-byteeeee** [comment]
已经弄了，现在还不准备更新，现在想用的话，可以用下面这个。
[build-artifacts.zip](https://github.com/user-attachments/files/18246604/build-artifacts.zip)
