### ISSUE TITLE
[功能请求]添加一个忽略假人召唤前缀或者后缀

### ISSUE THREAD

**Issue by Seungmin922** [Minecraft-AMS/Carpet-AMS-Addition#151]
有时候开了前缀，就召唤出有前缀的,特别东西在玩家身上.
权限等级默认是4.有0~4的选项。

**Comment by 1024-byteeeee** [comment]
如果是为了取出某真实玩家身上的东西，建议使用如：https://modrinth.com/mod/invview 之类的模组。
