### ISSUE TITLE
在v0.0.4中像1.15一样0t催熟仙人掌特性的问题

### ISSUE THREAD

**Issue by erduotong** [Minecraft-AMS/Carpet-AMS-Addition#2]
在Cactusfarm选项为true的时候，在一个仙人掌旁边放置一个方块（可以让仙人掌掉落的），仙人掌会弹出一个物品，有概率向上生长一格，仙人掌不掉落

**Comment by 1024-byteeeee** [comment]
> 在Cactusfarm选项为true的时候，在一个仙人掌旁边放置一个方块（可以让仙人掌掉落的），仙人掌会弹出一个物品，有概率向上生长一格，仙人掌不掉落落

已修复，没有变更版本号，重新下载0.0.4版本就行
