### ISSUE TITLE
1.19.2 request

### ISSUE THREAD

**Issue by woshikedayaa** [Minecraft-AMS/Carpet-AMS-Addition#21]
如题 很喜欢那个深板岩秒破的特性 但是苦于没有1.19.2的

请问能不能更新个1.19.2的

**Comment by 1024-byteeeee** [comment]
[Carpet-AMS-Addition-mc1.19.2-v1.3.11-SNAPSHOT.zip](https://github.com/Minecraft-AMS/Carpet-AMS-Addition/files/10881740/Carpet-AMS-Addition-mc1.19.2-v1.3.11-SNAPSHOT.zip)

**Comment by 1024-byteeeee** [comment]
1.3.11版本有问题，建议用1.3.12版本，并且在1.3.12版本开始会继续支持1.19,2
