### ISSUE TITLE
bellBlockChunkLoader 中可能的错误

### ISSUE THREAD

**Issue by SteveSimonFog** [Minecraft-AMS/Carpet-AMS-Addition#24]
开启bellBlockChunkLoader 之后 区块确实加载了 但是实体和漏斗的运作不正常[掉落物不消失 漏斗传输速度异常]测试方法:
![屏幕截图 2023-04-24 160946](https://user-images.githubusercontent.com/84281477/233944985-da4ae4a2-c137-4ccc-8ca7-80f808b84657.png)

**Comment by SteveSimonFog** [comment]
版本Carpet-AMS-Addition-mc1.19.2-v1.5.2

**Comment by SteveSimonFog** [comment]
经过严谨测试 主世界不会有问题 测试版本使用模组如下:
[minecraft-exported-logs-2023-04-24T17-45-07.log](https://github.com/Minecraft-AMS/Carpet-AMS-Addition/files/11308975/minecraft-exported-logs-2023-04-24T17-45-07.log)
![image](https://user-images.githubusercontent.com/84281477/233961664-605236d6-674b-4e25-bbed-6585aff49410.png)
掉落物在30分钟后未消失 漏斗传输5x64个物品在30分钟内未完成
![image](https://user-images.githubusercontent.com/84281477/233961970-436dff33-50de-47c2-b2f1-aa824b5a53fb.png)
即将测试末地情况

**Comment by SteveSimonFog** [comment]
实测 末地一样有问题 
![image](https://user-images.githubusercontent.com/84281477/233966070-53ce9798-a871-4631-8718-8a85eea60235.png)
![image](https://user-images.githubusercontent.com/84281477/233966079-1c2be05f-a175-403d-ac27-d3217208d5d8.png)

**Comment by SteveSimonFog** [comment]
音符盒区块加载 (noteBlockChunkLoader)有同样问题
![image](https://user-images.githubusercontent.com/84281477/233971653-c49619bf-a54a-4ddc-9d66-1e746529bada.png)
![image](https://user-images.githubusercontent.com/84281477/233971662-087a502c-3ad4-4c9e-95fc-8f718ac08257.png)
![image](https://user-images.githubusercontent.com/84281477/233971673-fe0447c1-f74c-49f3-ae48-bcd32cee067e.png)

**Comment by nirvanaxiao6** [comment]
请问在测试过程中是使用了Carpet-AMS-addition中的/chunkloading false功能取消自身的加载吗？可以使用carpet（不确定，也有可能是TIS-addition）带有的/log ticket xxx(使用TAB可以补全)来观察blockchunkloading给予加载票的运行情况。

**Comment by wendavid552** [comment]
应该是/log ticket bell_loader之类的，我粗看了一下直接相关的代码倒是没看出什么问题，待会在游戏内测试一下

**Comment by 1024-byteeeee** [comment]
我在1.19.4的版本中并未发现如上问题，1.19.2的版本无论是否有该问题我都不会进行处理，因为已经停止了对1.19.4以下的版本的更新。

**Comment by SteveSimonFog** [comment]
谢谢

1024_byteeeee ***@***.***> 于 2023年5月8日周一 下午10:06写道：

**Comment by SteveSimonFog** [comment]
没有

nirvanaxiao6 ***@***.***> 于 2023年4月25日周二 上午1:51写道：

**Comment by 1024-byteeeee** [comment]
不好意思，突然想起来很久以前你提过，这个问题已经解决了#41
