### ISSUE TITLE
amscarpet导致tnt无法被流体等防爆

### ISSUE THREAD

**Issue by IF-desu** [Minecraft-AMS/Carpet-AMS-Addition#25]
测试结果，版本1.16.5-1.11.1，ams默认没改过设置

**Comment by IF-desu** [comment]
![qrcode_1684657349956](https://github.com/Minecraft-AMS/Carpet-AMS-Addition/assets/86994398/2d7fbb14-ce74-4999-9d7e-18c51321ba1b)

**Comment by IF-desu** [comment]
> ![qrcode_1684657349956](https://user-images.githubusercontent.com/86994398/239729059-2d7fbb14-ce74-4999-9d7e-18c51321ba1b.jpg)

不知道为什么上传不了视频

**Comment by 1024-byteeeee** [comment]
已修复
