### ISSUE TITLE
[已解决]1.19.2   Supports

### ISSUE THREAD

**Issue by vocaloidkiss** [Minecraft-AMS/Carpet-AMS-Addition#36]
### Motivation

1.19.2   Supports

### Description

1.19.2   Supports

### Other information

1.19.2   Supports

**Comment by 1024-byteeeee** [comment]
This is the last Carpet AMS Addition that supports 1.19.2 .
<br/>
https://github.com/Minecraft-AMS/Carpet-AMS-Addition/releases/tag/v1.11.2%26v1.5.3
