### ISSUE TITLE
fabric1.20易碎黑曜石失效

### ISSUE THREAD

**Issue by jitui-star** [Minecraft-AMS/Carpet-AMS-Addition#37]
指令输入后 黑曜石硬度还是未改变

**Comment by 1024-byteeeee** [comment]
明天看🫰🏼

**Comment by 1024-byteeeee** [comment]
> 指令输入后 黑曜石硬度还是未改变

经测试没有问题哈，这个功能需要客户端与服务器同时支持哈，是不是服务器开启后你的客户端没有装Carpet AMS Addition呢？

**Comment by jitui-star** [comment]
好吧 我刚确认了一下 我仅仅服务端装了 客户端美妆



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年9月10日(星期天) 晚上11:04
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Minecraft-AMS/Carpet-AMS-Addition] fabric1.20易碎黑曜石失效 (Issue #37)





  
指令输入后 黑曜石硬度还是未改变
  
经测试没有问题哈，这个功能需要客户端与服务器同时支持哈，是不是服务器开启后你的客户端没有装Carpet AMS Addition呢？

**Comment by 1024-byteeeee** [comment]
> 
好的
