### ISSUE TITLE
游戏崩溃

### ISSUE THREAD

**Issue by Adogs1** [Minecraft-AMS/Carpet-AMS-Addition#39]
### Bug description

在加载了AMS后能成功启动游戏，但点击单人游戏时，会显示正在保存世界，然后退出客户端
启动器说是AMS兼容报错

### Steps to reproduce

如上
我也考虑到可能是我mod添加过多引起，后来我只留下Fabric api/carpet/AMS这三个mod测试，也还是因为报出AMS原因崩溃

### Relevant logs

https://mclo.gs/YW6Va9m

### Minecraft version

1.20.2

### TemplateMod version

2.10.1

### Check list

- [X] I have verified that the issue persists in the latest version of the mod.
- [X] I have searched the existing issues and confirmed that this is not a duplicate.

**Comment by Adogs1** [comment]
> ### Bug 描述
> 在加载了AMS后能成功启动游戏，但点击单人游戏时，会显示正在保存世界，然后退出客户端 启动器说是AMS兼容报错
> 
> ### 重现步骤
> 如上 我也考虑到可能是我mod添加过多引起，后来我只留下Fabric api/carpet/AMS这三个mod测试，也还是因为报出AMS原因崩溃
> 
> ### 预期行为
> _没有回应_
> 
> ### 实际行为
> _没有回应_
> 
> ### 相关日志
> https://mclo.gs/YW6Va9m
> 
> ### Minecraft版本
> 1.20.2
> 
> ### TemplateMod 版本
> 2.10.1
> 
> ### 其他资讯
> _没有回应_
> 
> ### 检查清单
> * [x] 我已经验证了该问题在最新版本的模组中仍然存在。
> * [x] 我已经搜索了现有问题并确认这不是重复的。

我查看了日志，可能是AMS在2.9.2使用Mixin功能导致的？

**Comment by 1024-byteeeee** [comment]
我刚看了，`opPlayerNoCheatExtra`  引起的，我现在弄........

**Comment by Adogs1** [comment]
> 我刚看了， 引起的，我现在弄........`opPlayerNoCheatExtra`
嗯，我使用了2.9.1版本没有出现这种问题

**Comment by 1024-byteeeee** [comment]
https://modrinth.com/mod/carpet-ams-addition/version/mc1.20.2-v2.10.2
