### ISSUE TITLE
Ideas

### ISSUE THREAD

**Issue by sternschnaube** [Minecraft-AMS/Carpet-AMS-Addition#41]
### Motivation

I love the rules!!

### Description

moveableAnvil exist two times, has to be fixed.

![image](https://github.com/Minecraft-AMS/Carpet-AMS-Addition/assets/120551916/d5b5b3b8-9594-43c9-ae83-4b085b26faa0)

Could you split fasterMovement please into three rules, one for each dimension? And maybe another for custom ones? :blush

**Comment by 1024-byteeeee** [comment]
收到，我会在下一个版本进行修复，对于fasterMovement我不是很明白您的意思。
Got it, I will fix it in the next release. Regarding "fasterMovement," I'm not quite clear on what you mean.

**Comment by 1024-byteeeee** [comment]
你的意思是说在下界，末地，主世界拥有不同的移动速度吗？
Are you suggesting having different movement speeds in the Nether, the End, and the Overworld?

不好意思，我的英文烂透了，这都是来自GPT的翻译，如果你不好理解可以尝试机翻我的中文。
I'm sorry, my English is terrible. This is all from GPT's translation. If you don't understand, you can try machine-translating my Chinese.

**Comment by sternschnaube** [comment]
Yep exactly this 😊
Overworld, Nether, End.

**Comment by 1024-byteeeee** [comment]
那么你想让这三个维度的移动速度与目前的Ⅰ Ⅱ Ⅲ如何对应呢？
So, how do you want the movement speeds in these three dimensions to correspond to the current I, II, III?

**Comment by sternschnaube** [comment]
fasterMovementOverworld
fasterMovementNether
fasterMovementEnd

I was testing swimming, speed III allows you to swim against bubbles 😂😂

**Comment by 1024-byteeeee** [comment]
hah，我会考虑你的提议，如果决定拓展他的话，我会在此基础上再增加几个离谱的挡位，在此之前我会保留这个issue。
hah, I will consider your suggestion. If I decide to expand on it, I will add a few more outrageous levels on top of this. Until then, I will keep this issue open.

**Comment by sternschnaube** [comment]
And what do you think about doubleShulkerBox rule? Equivalent to the doubleEnderChest one.

**Comment by 1024-byteeeee** [comment]
也是一个非常不错的点子，我会考虑添加它。
That's also a very good idea, I will consider adding it.

**Comment by sternschnaube** [comment]
Together with the stackableShulkerBox rule, very strong and solves much from the inventory space problems 😊

**Comment by 1024-byteeeee** [comment]
可能有点不原版但我喜欢它!
It might be a bit "NOT VANILLA", but I like it. HAH
