### ISSUE TITLE
carpet ams和carpet org不兼容/Carpet AMS and Carpet org are not compatible.

### ISSUE THREAD

**Issue by cdqtzrc** [Minecraft-AMS/Carpet-AMS-Addition#45]
### Motivation

我是carpet org addition的作者，carpet ams的“最大方块交互距离”似乎与carpet org的“最大方块交互距离”功能重复了，这导致两个Mod不兼容

### Description

<img width="1280" alt="屏幕截图 2023-11-25 003815" src="https://github.com/Minecraft-AMS/Carpet-AMS-Addition/assets/134773425/f8ed32c6-1d72-482a-a4db-2e3dc904cc18">
<img width="1280" alt="屏幕截图 2023-11-25 004106" src="https://github.com/Minecraft-AMS/Carpet-AMS-Addition/assets/134773425/be29d456-51ee-499e-8f44-d4cd363e38dc">

**Comment by 1024-byteeeee** [comment]
问题来自这里：

![1](https://github.com/Minecraft-AMS/Carpet-AMS-Addition/assets/77058327/572f69e9-54f7-4eb8-bd66-660d180c64ce)（1）

此处我使用了[MixinExtras](https://github.com/LlamaLad7/MixinExtras)的`@WrapOperation`注解所以不会与org carpet发生冲突：

![2](https://github.com/Minecraft-AMS/Carpet-AMS-Addition/assets/77058327/3f0136a4-3891-4032-83ec-6108bb9338ff)（2）

目前我将图（1）更换为了`@Inject`注解经过测试不会与org carpet发生冲突，会在下一个版本进行更新。

**Comment by cdqtzrc** [comment]
那规则名我改吧

**Comment by 1024-byteeeee** [comment]
> 那规则名我改吧

麻烦了 [抱拳]

**Comment by 1024-byteeeee** [comment]
public void processBlockBreakingAction(BlockPos pos, PlayerActionC2SPacket.Action action, Direction direction, int worldHeight) {
        double d = this.player.getX() - ((double)pos.getX() + 0.5);
        double e = this.player.getY() - ((double)pos.getY() + 0.5) + 1.5;
        double f = this.player.getZ() - ((double)pos.getZ() + 0.5);
        double g = d * d + e * e + f * f;
        if (g > 36.0) {
            BlockState blockState;
            if (this.player.world.getServer() != null && this.player.getChunkPos().getChebyshevDistance(new ChunkPos(pos)) < this.player.world.getServer().getPlayerManager().getViewDistance()) {
                blockState = this.world.getBlockState(pos);
            } else {
                blockState = Blocks.AIR.getDefaultState();
            }

            this.player.networkHandler.sendPacket(new PlayerActionResponseS2CPacket(pos, blockState, action, false, "too far"));
        } else if (pos.getY() >= worldHeight) {
            this.player.networkHandler.sendPacket(new PlayerActionResponseS2CPacket(pos, this.world.getBlockState(pos), action, false, "too high"));
        } else {
            BlockState blockState2;
            if (action == net.minecraft.network.packet.c2s.play.PlayerActionC2SPacket.Action.START_DESTROY_BLOCK) {
                if (!this.world.canPlayerModifyAt(this.player, pos)) {
                    this.player.networkHandler.sendPacket(new PlayerActionResponseS2CPacket(pos, this.world.getBlockState(pos), action, false, "may not interact"));
                    return;
                }

                if (this.isCreative()) {
                    this.finishMining(pos, action, "creative destroy");
                    return;
                }

                if (this.player.isBlockBreakingRestricted(this.world, pos, this.gameMode)) {
                    this.player.networkHandler.sendPacket(new PlayerActionResponseS2CPacket(pos, this.world.getBlockState(pos), action, false, "block action restricted"));
                    return;
                }

                this.startMiningTime = this.tickCounter;
                float h = 1.0F;
                blockState2 = this.world.getBlockState(pos);
                if (!blockState2.isAir()) {
                    blockState2.onBlockBreakStart(this.world, pos, this.player);
                    h = blockState2.calcBlockBreakingDelta(this.player, this.player.world, pos);
                }

                if (!blockState2.isAir() && h >= 1.0F) {
                    this.finishMining(pos, action, "insta mine");
                } else {
                    if (this.mining) {
                        this.player.networkHandler.sendPacket(new PlayerActionResponseS2CPacket(this.miningPos, this.world.getBlockState(this.miningPos), net.minecraft.network.packet.c2s.play.PlayerActionC2SPacket.Action.START_DESTROY_BLOCK, false, "abort destroying since another started (client insta mine, server disagreed)"));
                    }

                    this.mining = true;
                    this.miningPos = pos.toImmutable();
                    int i = (int)(h * 10.0F);
                    this.world.setBlockBreakingInfo(this.player.getId(), pos, i);
                    this.player.networkHandler.sendPacket(new PlayerActionResponseS2CPacket(pos, this.world.getBlockState(pos), action, true, "actual start of destroying"));
                    this.blockBreakingProgress = i;
                }
            } else if (action == net.minecraft.network.packet.c2s.play.PlayerActionC2SPacket.Action.STOP_DESTROY_BLOCK) {
                if (pos.equals(this.miningPos)) {
                    int j = this.tickCounter - this.startMiningTime;
                    blockState2 = this.world.getBlockState(pos);
                    if (!blockState2.isAir()) {
                        float k = blockState2.calcBlockBreakingDelta(this.player, this.player.world, pos) * (float)(j + 1);
                        if (k >= 0.7F) {
                            this.mining = false;
                            this.world.setBlockBreakingInfo(this.player.getId(), pos, -1);
                            this.finishMining(pos, action, "destroyed");
                            return;
                        }

                        if (!this.failedToMine) {
                            this.mining = false;
                            this.failedToMine = true;
                            this.failedMiningPos = pos;
                            this.failedStartMiningTime = this.startMiningTime;
                        }
                    }
                }

                this.player.networkHandler.sendPacket(new PlayerActionResponseS2CPacket(pos, this.world.getBlockState(pos), action, true, "stopped destroying"));
            } else if (action == net.minecraft.network.packet.c2s.play.PlayerActionC2SPacket.Action.ABORT_DESTROY_BLOCK) {
                this.mining = false;
                if (!Objects.equals(this.miningPos, pos)) {
                    LOGGER.warn("Mismatch in destroy block pos: {} {}", this.miningPos, pos);
                    this.world.setBlockBreakingInfo(this.player.getId(), this.miningPos, -1);
                    this.player.networkHandler.sendPacket(new PlayerActionResponseS2CPacket(this.miningPos, this.world.getBlockState(this.miningPos), action, true, "aborted mismatched destroying"));
                }

                this.world.setBlockBreakingInfo(this.player.getId(), pos, -1);
                this.player.networkHandler.sendPacket(new PlayerActionResponseS2CPacket(pos, this.world.getBlockState(pos), action, true, "aborted destroying"));
            }

        }
    }
使用@inject更改此处的g > 36 为自己的值

**Comment by 1024-byteeeee** [comment]
ok了
![{}$B5B`(Z0R{49Q1@}6%U5Y](https://github.com/Minecraft-AMS/Carpet-AMS-Addition/assets/77058327/a3f0f037-4e64-4a52-bafc-ea56b9e8cc0e)

**Comment by 1024-byteeeee** [comment]
Carpet AMS Addition v2.14.2 为兼容版本。

Carpet AMS Addition v2.14.2 is the compatible version.

https://minecraft-ams.github.io/carpetamsaddition/2023/11/25/v2.14.2/
