### ISSUE TITLE
最大方块交互距离更改时交互了两次

### ISSUE THREAD

**Issue by cdqtzrc** [Minecraft-AMS/Carpet-AMS-Addition#46]
### Bug description

最大方块交互距离启用时，拿着刷怪蛋点一下地面，生成了两只生物

### Steps to reproduce

1.拿一个刷怪蛋
2.将最大方块交互距离改成一个较大值（最好大于6）
3.拿刷怪蛋点一下近处的地面
或
1.找到一个活板门方块
2.点击一下活板门

### Expected behavior

生成一只生物
或
活板门打开

### Actual behavior

生成了两只生物
或
活板门打开后立即关闭

### Minecraft version

1.20.1

### TemplateMod version

Carpet-AMS-Addition v2.14.1

### Other information

解决方案：
<img width="811" alt="屏幕截图 2023-11-25 194310" src="https://github.com/Minecraft-AMS/Carpet-AMS-Addition/assets/134773425/0353d599-c2b7-4a56-b022-405ed8ed3b30">
interactBlock()方法调用了两次，一次是距离小于64.0时正常调用的，另一次是距离小于AmsServerSettings.maxBlockInteractionDistance时调用的

### Check list

- [X] I have verified that the issue persists in the latest version of the mod.
- [X] I have searched the existing issues and confirmed that this is not a duplicate.

**Comment by 1024-byteeeee** [comment]
十分感谢，v2.14.1更新之后服里有人发现跟我说了然后更了v2.14.1🤣，不过我是这样解决的：
![1](https://github.com/Minecraft-AMS/Carpet-AMS-Addition/assets/77058327/49a237f6-4f45-4916-8d48-3c92d1360647)（1）

**Comment by cdqtzrc** [comment]
但是还有一个小问题，在世界最高处以上放置方块时，会显示一条世界高度限制是319的警告信息，但是修改了交互距离后这条警告没有了

**Comment by 1024-byteeeee** [comment]
> 但是还有一个小问题，在世界最高处以上放置方块时，会显示一条世界高度限制是319的警告信息，但是修改了交互距离后这条警告没有了

这应该不是一个值得注意的问题我感觉，因为建筑高度本身就是319，你怎么看。🤔

**Comment by 1024-byteeeee** [comment]
> 不想改就算了，毕竟这个bug并不严重

是的，org carpet有计划做低版本支持吗，有的话如下部分我也要做对应修改....

![1](https://github.com/Minecraft-AMS/Carpet-AMS-Addition/assets/77058327/6b55f223-0acb-464a-811f-4cee8767d65c)(1)

**Comment by cdqtzrc** [comment]
目前没有，估计以后也不会有

**Comment by 1024-byteeeee** [comment]
> 目前没有，估计以后也不会有

那我暂时先不动了，虽然它有兼容性上的问题但是我感觉这里用 `@ModifyConstant` 比 `@Inject` 更好。

**Comment by 1024-byteeeee** [comment]
> 还有件事，在提交这个bug之前我是看了更新日志的，但是你似乎没有把问题描述清除 <img alt="image" width="890" src="https://private-user-images.githubusercontent.com/134773425/285592199-55ba5c9a-ab6c-48fc-a1e2-1bc3993de370.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDA5MTcyNDEsIm5iZiI6MTcwMDkxNjk0MSwicGF0aCI6Ii8xMzQ3NzM0MjUvMjg1NTkyMTk5LTU1YmE1YzlhLWFiNmMtNDhmYy1hMWUyLTFiYzM5OTNkZTM3MC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMTI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTEyNVQxMjU1NDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hMzdkMTk3Y2EwYzNlNjlhNDRhYWU0MmYxOGE3MmMxN2U0NmFhODU4ZmQzYTRiOGQ3NjRmMGZlMTJjM2E2ZDFmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.wnzv8DZsNOxdr1mpDeIGaGWBRbVI2VutsA3tCNNu0nM">

是的，现在看来我的描述应该是有错误的，这并不属于兼容性问题（因为成员发现后我随便放了两个方块只是快速放置会放两次，正常对地板放没有问题），我现在修改日志。
