### ISSUE TITLE
关于移除enhancedWorldEater

### ISSUE THREAD

**Issue by Adogs1** [Minecraft-AMS/Carpet-AMS-Addition#47]
### Motivation

我不能明白为什么要移除enhancedWorldEater规则
如果使用WorldEater
那么customBlowUpBlock将设置除铁砧和基岩以外的所有方块，
它使它使用WorldEater变得更麻烦
所有我会选择保留v2.15.0更新

### Description

同时保留以上两个规则。如果可能的话，在使用一个时自动关闭另一个。

**Comment by 1024-byteeeee** [comment]
uh，我想的是enhancedWorldEater规则的作用完全可以通过customBlowUpBlock规则多设置几个可能会遇到的不可炸毁方块来达到相同的目的，只是变得麻烦了，不过看来你很喜欢enhancedWorldEater规则，所以我会在下个版本重新添加这个规则，同时我计划把其他方块的爆炸抗性设置为用户可自定义的，在下个版本更新之前我会保留这个issue。☺

**Comment by 1024-byteeeee** [comment]
### Changelog
#### https://minecraft-ams.github.io/carpetamsaddition/2023/12/08/v2.16.1/

### Download
#### https://modrinth.com/mod/carpet-ams-addition/versions

**Comment by 1024-byteeeee** [comment]
> > ### 更改日志
> > #### https://minecraft-ams.github.io/carpetamsaddition/2023/12/08/v2.16.1/
> > ### 下载
> > #### https://modrinth.com/mod/carpet-ams-addition/versions
> 
> 谢谢！

不客气
