### ISSUE TITLE
更好的香草的物品漏斗分类

### ISSUE THREAD

**Issue by Adogs1** [Minecraft-AMS/Carpet-AMS-Addition#48]
### Motivation

如果可以的话，通过漏斗最后一格放置规则指定物品（不限数量），能使该漏斗其他格子输出到只剩下一个物品时自动锁住该槽位，之后不会输出该槽位的最后一个物品（包括如果它下方还有一个漏斗的话，也无法吸收），但可以继续吸收上方物品掉落物或容器，然后大于1个物品，继续输出。这样以实现原版物品分类的功能

### Description

简单的说就是，当满足条件时，其他槽内物品都会留下一个物品以从上方获得指定的物品，并继续输出，在输出时（包括它主动输出和下方漏斗吸收它），当第一个槽剩下一个物品时，就开始尝试第二个物品槽的输出（即不让下方漏斗知道上方槽位都留有一个物品而去反复吸收它，就是留有一个物品时，让下方漏斗以为它是空的，减少运算）（符合原版），它可以实现在漏斗和漏斗矿车上，从而实现原版的高效物品分类

**Comment by 1024-byteeeee** [comment]
emmm...
 总结一下：
- 通过判断漏斗内的某个槽位的是什么物品来让漏斗只能吸取该物品。
- 漏斗会留下所设定的那个槽位的最后一个。
- 留有最后一个物品时漏斗的状态为空。

是这个意思吗？

**Comment by Adogs1** [comment]
> emmm... 总结一下：
> 
> * 通过判断漏斗内的某个槽位的是什么物品来让漏斗只能吸取该物品。
> * 漏斗会留下所设定的那个槽位的最后一个。
> * 留有最后一个物品时漏斗的状态为空。
> 
> 是这个意思吗？
> 
> So, to summarize:
> 
> * By determining what item is in a specific slot within the hopper, the hopper can be made to only collect that item.
> * The hopper will retain the last item in the designated slot.
> * When the last item is retained, the hopper's state is considered empty.
> 
> Is that the idea?
> 
> Translate into English from Chat-GPT hah

是的
通过判断漏斗内的某个槽位的是什么物品来让漏斗只能吸取该物品。——这个是原版漏斗功能
留有最后一个物品时漏斗的状态为空——这个只是在漏斗启用这个规则后，下方如果是漏斗，可以减少很多不必要的运算，它应该不影响一些原版的其他功能，如比较器能正常检测输出红石信号等，当然，如果代码不好分开写，一起写也能接受！

**Comment by 1024-byteeeee** [comment]
我认为原版科技树的储存科技已经足够高效了，并不需要这样来让漏斗更好用，或者说我感觉这样不如通过造一些机器来进行高效的物品分类。

**Comment by 1024-byteeeee** [comment]
> > emmm... 总结一下：
> > 
> > * 通过判断漏斗内的某个槽位的是什么物品来让漏斗只能吸取该物品。
> > * 漏斗会留下所设定的那个槽位的最后一个。
> > * 留有最后一个物品时漏斗的状态为空。
> > 
> > 是这个意思吗？
> > So, to summarize:
> > 
> > * By determining what item is in a specific slot within the hopper, the hopper can be made to only collect that item.
> > * The hopper will retain the last item in the designated slot.
> > * When the last item is retained, the hopper's state is considered empty.
> > 
> > Is that the idea?
> > Translate into English from Chat-GPT hah
> 
> 是的 通过判断漏斗内的某个槽位的是什么物品来让漏斗只能吸取该物品。——这个是原版漏斗功能 留有最后一个物品时漏斗的状态为空——这个只是在漏斗启用这个规则后，下方如果是漏斗，可以减少很多不必要的运算，它应该不影响一些原版的其他功能，如比较器能正常检测输出红石信号等，当然，如果代码不好分开写，一起写也能接受！

我认为原版科技树的储存科技已经足够高效了，并不需要这样来让漏斗更好用，或者说我感觉这样不如通过造一些机器来进行高效的物品分类。
