### ISSUE TITLE
Question about maxPlayerInteractionDistance

### ISSUE THREAD

**Issue by sternschnaube** [Minecraft-AMS/Carpet-AMS-Addition#50]
### Motivation

/

### Description

I was not testing this version yet, but does this mean I can now attack entities from far away?

If yes, could you please split this rule separately? Higher distance for breaking blocks is great, but a higher attack reach results into a bad gameplay >>> fighting against mobs is then not balanced anymore.

Thanks 😊

**Comment by 1024-byteeeee** [comment]
我明白你的意思，我也想过是否要拆成两个规则，但我认为这两个应该是要同步受到更改的，如果你希望只修改方块最大的放置距离而不修改与实体交互的距离的话可以使用Carpet Org Addition，其中有一样的功能且支持单独修改，与我的唯一区别是最大距离只有128。

Link: https://modrinth.com/mod/carpet-org-addition

**Comment by 1024-byteeeee** [comment]
> 我明白你的意思，我也想过是否要拆成两个规则，但我认为这两个应该是要同步受到更改的，如果你希望只修改方块最大的放置距离而不修改与实体交互的距离的话可以使用Carpet Org Addition，其中有一样的功能且支持单独修改，与我的唯一区别是最大距离只有128。
> 
> 友情链接： https://modrinth.com/mod/carpet-org-addition

**Comment by 1024-byteeeee** [comment]
> 我明白你的意思，我也想过是否要拆成两个规则，但我认为这两个应该是要同步受到更改的，如果你希望只修改方块最大的放置距离而不修改与实体交互的距离的话可以使用Carpet Org Addition，其中有一样的功能且支持单独修改，与我的唯一区别是最大距离只有128。
> 
> 友情链接： https://modrinth.com/mod/carpet-org-addition

I understand what you mean, and I have also considered whether to split it into two rules. However, I believe that these two should be changed synchronously. If you only want to modify the maximum placement distance of blocks without modifying the distance for interacting with entities, you can use Carpet Org Addition, which has the same functionality and supports separate modifications. The only difference is that the maximum distance is limited to 128.

**Comment by sternschnaube** [comment]
Interesting, thanks for letting me know.

It's your decision to close it then 😊

I believe that no one is really going over 20, maximum 😂
I have found 8,5 as sweet spot for me.

**Comment by 1024-byteeeee** [comment]
> 有趣，谢谢你让我知道。
> 
> 然后😊由您决定关闭它
> 
> 我相信没有人真的会超过 20 岁，因为我发现 8,5 😂 对我来说是甜蜜点。

是的，我自己也是使用的8.5，我只是为了适配tweakeroo的功能hah

---

Yes, I'm using 8.5 myself as well. I just wanted to adapt the functionality of Tweakeroo, hah
