### ISSUE TITLE
Put Vanilla enchantments up to level V

### ISSUE THREAD

**Issue by sternschnaube** [Minecraft-AMS/Carpet-AMS-Addition#51]
### Motivation

It feels more fitting to me.

### Description

Really important to me:
Respiration III >>> V
Unbreaking III >>> V

Movespeed enchants:
Depth Strider III >>> V
Soul Speed III >>> V
Swift Sneak III >>> V

Protection ones:
Feather Falling IV >>> V
Protection IV >>> V 
(All other three protection enchants.)

Damage category:
Piercing IV >>> V

Single rules for every enchantment would be great, and or a custom menu for activation.

I'm not sure if I want them to be added to the Loot Table, Villager trades - maybe it's not possible to deactivate.

**Comment by 1024-byteeeee** [comment]
这是一个不错的点子，但是这个功能不能放在carpet拓展中，原版游戏中不存在水下呼吸Ⅴ的附魔书。
---
This is a good idea, but this feature cannot be included in the Carpet extension as there is no Enchanted Book of Respiration  V in the vanilla game.

**Comment by sternschnaube** [comment]
Not sure if the translation was wrong, but it says "there is no Respiration V book in Vanilla". It's only level III 😂

**Comment by 1024-byteeeee** [comment]
> Not sure if the translation was wrong, but it says "there is no Respiration V book in Vanilla". It's only level III as mentioned in my initial message 😂

是的，就是那个意思，我不能在carpet拓展模组中注册一个新的物品，这对于carpet拓展来说是不合理的。

---

Yes, that's exactly what I mean. I can't register a new item in the Carpet extension mod, which is unreasonable for the Carpet extension.

**Comment by sternschnaube** [comment]
That means it's only limited to Respiration III, or all other enchantments?

**Comment by 1024-byteeeee** [comment]
简单的来说，就是这个功能更适合一些独立模组来做。

---

Simply put, this feature is better suited for independent mods to implement.
