### ISSUE TITLE
Budding Amethyst mining speed

### ISSUE THREAD

**Issue by sternschnaube** [Minecraft-AMS/Carpet-AMS-Addition#52]
### Motivation

Preventing unwanted block breaks.

### Description

Change the block hardness from Budding Amethyst to the level of Obsidian.

**Comment by 1024-byteeeee** [comment]
我会考虑在下次更新中制作这个规则。

---

I will consider implementing this rule in the next update.

**Comment by wendavid552** [comment]
As kind of substitution, you could try this client side mod here: [Oh my minecraft client](https://modrinth.com/mod/oh-my-minecraft-client). You could customize blacklists of breaking blocks.

**Comment by sternschnaube** [comment]
Thanks, I know a few mods / or remembered that. I still hope it can make it into AMS. If it works as server-side feature, it would be fantastic.

**Comment by 1024-byteeeee** [comment]
### Changelog
#### https://minecraft-ams.github.io/carpetamsaddition/2023/12/25/v2.21.0/

**Comment by sternschnaube** [comment]
Tested it right now - you was creating a powerful rule which is future proof. Thank you so much, no unintentional breaks of Budding Amethyst anymore 🥳
