### ISSUE TITLE
Survival use of Lights and Barrier blocks

### ISSUE THREAD

**Issue by sternschnaube** [Minecraft-AMS/Carpet-AMS-Addition#53]
### Motivation

That's very useful blocks but limited to creative access.

### Description

I can add the crafting recipes with an Datapack.
What is needed is that a Survival player can mine those blocks.
Maybe if he holds the specific block in his second hand.

**Comment by 1024-byteeeee** [comment]
我会考虑在下次更新中制作这个规则。

---

I will consider implementing this rule in the next update.

**Comment by wendavid552** [comment]
In fact you could break these blocks by the same method breaking bedrocks and there are some client-side mods could easily mine bedrocks.

**Comment by 1024-byteeeee** [comment]
### Changelog
#### https://minecraft-ams.github.io/carpetamsaddition/2023/12/25/v2.21.0/
