### ISSUE TITLE
Remove Item cooldown

### ISSUE THREAD

**Issue by sternschnaube** [Minecraft-AMS/Carpet-AMS-Addition#54]
### Motivation

Feels better without, and it was normal vanilla behaviour in the past.

### Description

Remove the item cooldown from Items like Ender Pearls, Goat Horns, etc.

**Comment by 1024-byteeeee** [comment]
我会考虑在下次更新中制作这个规则。

---

I will consider implementing this rule in the next update.

**Comment by 1024-byteeeee** [comment]
### Changelog
#### https://minecraft-ams.github.io/carpetamsaddition/2023/12/25/v2.21.0/

**Comment by sternschnaube** [comment]
Works great, just the item delay overlay in the hotbar is still visible. But that's nothing. Thanks!!
