### ISSUE TITLE
bambooCollisionBoxDisabled rule but for Leaves

### ISSUE THREAD

**Issue by sternschnaube** [Minecraft-AMS/Carpet-AMS-Addition#55]
### Motivation

It's one of the best rules - why not for Leaves as well to optimize Horse riding and Elytra flying.

### Description

A menu to manage every Leaf block on it's own would be great / separated rules for each Leave block.

**Comment by 1024-byteeeee** [comment]
这条规则只是为了让我穿越竹林的时候不会被挤来挤去的，暂时不考虑对齐做出拓展。

---

This rule is just to prevent me from being squeezed while passing through the bamboo forest. I am not considering expanding it for alignment at the moment.

**Comment by sternschnaube** [comment]
Yep, and it does wonders. The same I would wish for forests \ leaves. But I understand you. 
Closed then 😊
