### ISSUE TITLE
Minecarts with custom Blocks

### ISSUE THREAD

**Issue by sternschnaube** [Minecraft-AMS/Carpet-AMS-Addition#56]
### Motivation

It's possible to spawn Minecarts with a custom Blocks into them with commands.

### Description

I would love to have it Survival friendly. Maybe right-click with a block in the hand does already the job. It would be an fantastic rule!

**Comment by 1024-byteeeee** [comment]
同 #57 

---

same #57

**Comment by sternschnaube** [comment]
Thanks for the fast response, I closed every denied ticket now.
I will come up with new ideas 😊
