### ISSUE TITLE
More hearts with Netherite Armor 

### ISSUE THREAD

**Issue by sternschnaube** [Minecraft-AMS/Carpet-AMS-Addition#57]
### Motivation

I want to integrate a higher maximum of hearts.

### Description

You have a total of 20 hearts. Which divides good against 4 (Armor pieces).
With a full set of Netherite Armor, we are doubling the hearts to an total of 40. Every piece adds 5 heart points (2 and a half).
I think it should only working on Netherite Armor. Maybe the armor needs Protection IV as enchantment too?

I'm interested to hear your opinion about it.

**Comment by 1024-byteeeee** [comment]
uh, 我认为这更像是其他的一些独立模组会去做的事情，我不会尝试制作这个规则。

---

uh, I think this is more like something other independent modules would do, and I wouldn't attempt to create this rule.
