### ISSUE TITLE
Custom block list for Ender Dragon 

### ISSUE THREAD

**Issue by sternschnaube** [Minecraft-AMS/Carpet-AMS-Addition#58]
### Motivation

/

### Description

Would be cool to have more blocks the Ender Dragon can't destroy.

**Comment by cdqtzrc** [comment]
其实你可以使用数据包实现同样的功能

**Comment by wendavid552** [comment]
Translation to the comment above: You could customize it with a **datapack**.

**Comment by 1024-byteeeee** [comment]
当然，我还是制作了一个末影龙不能破坏所有方块的规则，会在下个版本更新。

---

Of course, I've also implemented a rule where the Ender Dragon cannot destroy all blocks, which will be updated in the next version.

**Comment by sternschnaube** [comment]
Sounds great 😄

**Comment by 1024-byteeeee** [comment]
### Changelog
#### https://minecraft-ams.github.io/carpetamsaddition/2023/12/31/v2.22.0/
