### ISSUE TITLE
Elytra fly speed

### ISSUE THREAD

**Issue by sternschnaube** [Minecraft-AMS/Carpet-AMS-Addition#59]
### Motivation

/

### Description

A small boost would be great - something similar to movespeed from I to III, or even V :blus

**Comment by wendavid552** [comment]
Boosting elytra flying speed would crash the server and client. If you need a faster method, you could try:
1. ice boating
2. pearl cannon
3. mods like AutoPilot, which is a client mod automatically fly to a position with vanilla feature, using no fireworks, just self boosting with elytra, even faster than elytra with fireworks (With totally vanilla feature, but it manipulates your client).
4. /tp
