### ISSUE TITLE
"dispensersSetPlayerSpawn"

### ISSUE THREAD

**Issue by sternschnaube** [Minecraft-AMS/Carpet-AMS-Addition#61]
### Motivation

Sounds like a great new mechanic.

### Description

I think the Dispenser needs to have a player head in his inventory. Then it works in front of a bed. Same mechanic for Nether Respawn Anchor if possible.

Or maybe split it into DispensersSetPlayerSpawnOverworld / DispensersSetPlayerSpawnNether - something like this 😄

**Comment by 1024-byteeeee** [comment]
Hold on, bro, I need to take a break. QWQ

**Comment by sternschnaube** [comment]
Of course, you have all the time.

Do you think it's better to open just one ticket with multiple ideas for the future? I thought it's maybe more clear if every idea gets it's own one.

**Comment by 1024-byteeeee** [comment]
Honestly, there are advantages to both approaches, but I lean towards putting multiple ideas into one issue.

> Of course, you have all the time.
> 
> Do you think it's better to open just one ticket with multiple ideas for the future? I thought it's maybe more clear if every idea gets it's own one.

Honestly, there are advantages to both approaches, but I lean towards putting multiple ideas into one issue.

**Comment by sternschnaube** [comment]
Good, future ideas will be bundled into one ticket 😄

**Comment by wendavid552** [comment]
Could you explain more about your ideas? Will the dispenser refill with player heads? Does it enable automatically or must be powered? How to make someone respawn as you wish in your designing? Perhaps you could write more details about it.

Also to my own, it is not very hard to build a respawn anchor, and automatically refill it. Why would you request this feature?

And, multiple ideas in one ticket could be confusing. Open a discussion thread could be better if you wish?

**Comment by sternschnaube** [comment]
I write later more details about it.

I think a discussion thread would be a really great idea 💡
Thanks!!

**Comment by sternschnaube** [comment]
About DispensersSetPlayerSpawnBed:
- I came up with a Player Head as simple solution, to define which player has registered this Dispenser - it could also be expanded to more players (since there are 9 slots) 
- It has to be powered yes, that's the main idea behind it. People could activate it on a server for you and the end portal works like a better portal this way.
- The respawn works just as vanilla, nothing more.

About DispensersSetPlayerSpawnNetherAnchor:
- I'm sorry, at the moment I wrote this idea, I just thought to include the Nether too. Now after thinking more detailed about it, it's already possible to set manually the Nether Spawn if you registered the Anchor.
- But my idea could still be useful, as that you can register the Anchor the same way as with the Beds. And refilling works as like vanilla.
(I never used the Respawn Anchor myself, that's the reason why my first idea was lacking 😂)

New to this list: DispensersSetPlayerSpawnCampfire
- There exist a carpet rule which allows to set Campfires as respawn point. 
- If the base rule is active, you are allowed to use DispensersSetPlayerSpawnCampfire.

There should be existing already rules for Player Head drop mechanics (other mods allowing this), otherwise include this  as new base rule that everything can work.

Love to hear your opinion(s) about it 😊

**Comment by 1024-byteeeee** [comment]
It seems to have no particularly meaningful purpose. 😕

**Comment by sternschnaube** [comment]
Good, I will come up in the future with new ideas 😄
