### ISSUE TITLE
Custom block hardness doesn't work with newer release

### ISSUE THREAD

**Issue by sternschnaube** [Minecraft-AMS/Carpet-AMS-Addition#79]
### Bug description

- I have the rule "customBlockHardness" set to true

![image](https://github.com/Minecraft-AMS/Carpet-AMS-Addition/assets/120551916/a734b704-0fa8-41b5-ae47-92d1eb7e578d)

- Defined the block of my wishes and put a high value

![image](https://github.com/Minecraft-AMS/Carpet-AMS-Addition/assets/120551916/9336d38e-9d5b-4a59-a9be-20bdc7ae4358)

The version before, without the command enhancement, worked just fine.
I hope for a solution 😊 

### Steps to reproduce

/

### Minecraft version

1.20.2

### TemplateMod version

Carpet-AMS-Addition v2.22.0

### Check list

- [X] I have verified that the issue persists in the latest version of the mod.
- [X] I have searched the existing issues and confirmed that this is not a duplicate.

**Comment by 1024-byteeeee** [comment]
Sorry, I don't quite understand what you mean. 😅

**Comment by sternschnaube** [comment]
It just does not work - but all requirements should be set correctly:/

**Comment by 1024-byteeeee** [comment]
> 它只是不起作用 - 但所有要求都应该正确设置：/

![1](https://github.com/Minecraft-AMS/Carpet-AMS-Addition/assets/77058327/5c9a4dd3-c6ad-4b44-a644-5d570827e633)

The test on my end is successful. 😯

**Comment by 1024-byteeeee** [comment]
> > 它只是不起作用 - 但所有要求都应该正确设置：/
> 
> ![1](https://private-user-images.githubusercontent.com/77058327/293695591-5c9a4dd3-c6ad-4b44-a644-5d570827e633.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQyMDAxOTcsIm5iZiI6MTcwNDE5OTg5NywicGF0aCI6Ii83NzA1ODMyNy8yOTM2OTU1OTEtNWM5YTRkZDMtYzZhZC00YjQ0LWE2NDQtNWQ1NzA4MjdlNjMzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTAyVDEyNTEzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFhNDM1N2Y2ZWY4NjY2NDI4MzczMzcwN2I1NWY0ZTAyMDU4NDM3YjZmNWJiNmFmZmNiN2FiZWRhNTc4NGE4ZGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.RpNFvTGR6bGCopn8Wxfwwikl28Ttfme2hL22L-Wv1ho)
> 
> The test on my end is successful. 😯

uh~, the translation key has an issue. Let's fix it in the next version, but the functionality is not affected.

**Comment by wendavid552** [comment]
If you still have the issue, please provide us with your **logs** and **mods list**

**Comment by 1024-byteeeee** [comment]
I have identified an issue; currently, this rule only functions correctly on the client side...

**Comment by sternschnaube** [comment]
Thank you for confirming it, I was about to investigate in about a day again on it.
Good that the issue was spotted now 😄

**Comment by 1024-byteeeee** [comment]
> 谢谢你的确认，我打算在大约一天后再次调查它。很高兴现在发现了😄这个问题

This issue may not be easy to fix.......

**Comment by sternschnaube** [comment]
If nothing helps - revert back to the version without the commands. 
It looses a bit from elegance, but at least the effectivity is still present as it was before.

**Comment by 1024-byteeeee** [comment]
> If nothing helps - revert back to the version without the commands. It looses a bit from elegance, but at least the effectivity is still present as it was before.

maybe

**Comment by sternschnaube** [comment]
I think it was "Carpet AMS Addition v2.21.0".
Thanks again for all the effort - that's one of the most useful rules of your great mod.

**Comment by 1024-byteeeee** [comment]
> 我认为是“Carpet AMS Addition v2.21.0”。再次感谢您的所有努力 - 这是您伟大的模组中最有用的规则之一。

No, I killed her.     T.T

**Comment by 1024-byteeeee** [comment]
# Today I made a painful and difficult decision

### Changelog
#### https://minecraft-ams.github.io/carpetamsaddition/2024/01/04/v2.24.0/
&emsp;
&emsp;
@1024-byteeeee

**Comment by sternschnaube** [comment]
For my understanding, the rule is fixed now but other rules had to be removed for that?

But that's all rules anyway who involving in some ways the Block hardness / I see no issue there, it all can be defined with the single rule. Or I am wrong?

**Comment by 1024-byteeeee** [comment]
According to our tests, it seems that modifying block hardness series rules is not suitable to be placed within Carpet. When the server has rules enabled but the client does not have the Carpet AMS addition installed, the performance of players digging blocks becomes quite problematic. We cannot guarantee that all players joining the server have installed the Carpet AMS addition.

This passage is machine-translated, I suggest translating my Chinese.

---

根据我们的测试来看，修改方块硬度系列规则不适合放在carpet里面，当服务器开启规则客户端却没有安装carpet ams addition时玩家挖掘方块的表现很一言难尽，我们无法保证所有加入服务器的玩家都安装了carpet ams addition。

**Comment by sternschnaube** [comment]
But it's still present yes?
Otherwise I have to downgrade.

**Comment by 1024-byteeeee** [comment]
> 但它仍然存在，是吗？否则我必须降级。

Past versions will not be deleted, but it is not recommended to install and use them on a multi-user server.

**Comment by 1024-byteeeee** [comment]
In the future, I may turn this rule into a mod dedicated for the client side. ( ? )

**Comment by sternschnaube** [comment]
Just add a warning message and everything is fine. Why is there never trust and just giving it over to the server owners? Makes no sense to me.

But thanks for all the work you have done 😊

**Comment by 1024-byteeeee** [comment]
Hmm, I cannot guarantee that all users will pay attention to that warning message.

**Comment by sternschnaube** [comment]
This is not something on you, this is something the server community has to manage. 

You are not responsible for that. You gave the mod, the information, that's more than enough.

**Comment by 1024-byteeeee** [comment]
Maybe,  It seems reasonable, but I won't consider recalling them at the moment until I find a way that I think is better to implement them.

**Comment by sternschnaube** [comment]
I think the smoothest solution.

Make it work like the reachDistance rule. It only works if the client has the mod present.

**Comment by 1024-byteeeee** [comment]
I don't know if this can be done because these two things are not the same.

**Comment by sternschnaube** [comment]
That's true. For me it's not a loss, I downgrade now. And it's working for now until 1.20.4.

Hoping for a better solution.

This rule is more worth than everything else which came with the newer updates - for me.

**Comment by Adogs1** [comment]
> 我不知道这是否可以做到，因为这两件事并不相同。

请问要使用enhancedWorldEater，默认是-1，应该修改到0-16的多少？中文的翻译似乎有点看不懂，谢谢

**Comment by 1024-byteeeee** [comment]
> > 我不知道这是否可以做到，因为这两件事并不相同。
> 
> 
> 
> 请问要使用enhancedWorldEater，默认是-1，应该修改到0-16的多少？中文的翻译似乎有点看不懂，谢谢

0-16是其他方块的爆炸抗性，建议0-5之间。

**Comment by Adogs1** [comment]
> > > 我不知道这是否可以做到，因为这两件事并不相同。
> > 
> > 
> > 请问要使用enhancedWorldEater，默认是-1，应该修改到0-16的多少？中文的翻译似乎有点看不懂，谢谢
> 
> 0-16是其他方块的爆炸抗性，建议0-5之间。

谢谢
