### ISSUE TITLE
开启更新抑制崩溃修复（amsUpdateSuppressionCrashFix）会导致黑曜石无法正常生成

### ISSUE THREAD

**Issue by ImYiFeng** [Minecraft-AMS/Carpet-AMS-Addition#83]
### Bug description

开启更新抑制崩溃修复后，用水浇在岩浆上无法生成黑曜石而是生成圆石
![image](https://github.com/Minecraft-AMS/Carpet-AMS-Addition/assets/70053196/85973fda-6c57-4411-991f-7fdb0e564319)
备注：

### Steps to reproduce

1.创建世界
2.开启amsUpdateSuppressionCrashFix功能
3.找到一个岩浆湖，用水浇在上面，只能生成圆石而不是黑曜石

### Minecraft version

1.20.1

### TemplateMod version

2.24.0

### Check list

- [X] I have verified that the issue persists in the latest version of the mod.
- [X] I have searched the existing issues and confirmed that this is not a duplicate.

**Comment by 1024-byteeeee** [comment]
提供一下carpet ams addition的版本。

**Comment by ImYiFeng** [comment]
补充：经测试，用流动的水浇在岩浆源上无法正常生成黑曜石。但通过岩浆桶，把岩浆放置在静止的水池中，可以生成黑曜石

**Comment by ImYiFeng** [comment]
> 提供一下carpet ams addition的版本。

2.24.0，Issue里有写

**Comment by 1024-byteeeee** [comment]
> > 提供一下carpet ams addition的版本。
> 
> 2.24.0，Issue里有写

我的，没看见，升级至v2.25.0及以上 #82
https://minecraft-ams.github.io/carpetamsaddition/2024/01/09/v2.25.0/

**Comment by ImYiFeng** [comment]
> > > 提供一下carpet ams addition的版本。
> > 
> > 
> > 2.24.0，Issue里有写
> 
> 我的，没看见，升级至v2.25.0及以上 #82 https://minecraft-ams.github.io/carpetamsaddition/2024/01/09/v2.25.0/

好的，虽然不理解这两个bug有什么相似之处，但感谢解答。另外为作者效率点赞👍

**Comment by 1024-byteeeee** [comment]
> > > > 提供一下carpet ams addition的版本。
> > > 
> > > 
> > > 2.24.0，Issue里有写
> > 
> > 
> > 我的，没看见，升级至v2.25.0及以上 #82 https://minecraft-ams.github.io/carpetamsaddition/2024/01/09/v2.25.0/
> 
> 好的，虽然不理解这两个bug有什么相似之处，但感谢解答。另外为作者效率点赞👍

😄 不是一个问题，是由同一个失误引起的。
