### ISSUE TITLE
Anyone can view one's position without admission and unable to recognize

### ISSUE THREAD

**Issue by wendavid552** [Minecraft-AMS/Carpet-AMS-Addition#84]
### Motivation

When using `/where`, you can know the position of any other player in multiplayer game, and unlike other mods or plugin providing this feature, this command is totally secret to the player you get the position, which is more like stoling the position of others.  I would say this is more like a bug than a pretended feature as only who use `/where` knows about it.

### Description

Requiring for admisison or tell the player that someone is gonna getting the position.

**Comment by 1024-byteeeee** [comment]
### Changelog
#### https://minecraft-ams.github.io/carpetamsaddition/2024/01/18/v2.27.1/
