### ISSUE TITLE
Respawning Enderdragon Egg could set blocks in chunks not loaded

### ISSUE THREAD

**Issue by wendavid552** [Minecraft-AMS/Carpet-AMS-Addition#85]
### Bug description

In Respawnable Enderdragon Egg rule, the enderdragon egg is added too early without checking the UUID of the dragon entities. Suppose the ender dragon is teleported, and then killed in far away chunks, this feature will still modify the chunk remotely.

### Steps to reproduce

1. Create a new world
2. Enable the regeneratingDragonEgg
3. Go into the end, freeze the enderdragon and push it into unloaded chunks(or you can teleport it away)
4. New dragoneggs actually respawned

### Expected behavior

New dragoneggs do not respawn until we kill the new one

### Minecraft version

Any

### TemplateMod version

newest

### Check list

- [X] I have verified that the issue persists in the latest version of the mod.
- [X] I have searched the existing issues and confirmed that this is not a duplicate.

**Comment by 1024-byteeeee** [comment]
### Changelog
#### https://minecraft-ams.github.io/carpetamsaddition/2024/01/18/v2.27.1/
