### ISSUE TITLE
bedrockFlying not working in mutliplayer server

### ISSUE THREAD

**Issue by wendavid552** [Minecraft-AMS/Carpet-AMS-Addition#86]
### Bug description

`bedrockFlying` not working within a multiplayer server.

### Steps to reproduce

1. Create a server with Carpet-AMS-Addition
2.  Enable the `bedrockFlying` feature
3. Fly, but you will not stop after you stop inputing.

### Expected behavior

Stop after inputing.

### Minecraft version

1.18.2

### TemplateMod version

newest

### Other information

Could refer to similar features from Carpet-TIS-Addition, and injecting a client entity does not work for multiplayer server, you should injecting the ticking of a server entity

### Check list

- [X] I have verified that the issue persists in the latest version of the mod.
- [X] I have searched the existing issues and confirmed that this is not a duplicate.

**Comment by 1024-byteeeee** [comment]
need client support.
