### ISSUE TITLE
enderDragonNoDestroyBlock causes enderdragon does not slow down when going through blocks

### ISSUE THREAD

**Issue by wendavid552** [Minecraft-AMS/Carpet-AMS-Addition#88]
### Bug description

Enderdragon will go through blocks slower in vanilla when going through blocks(No matter breakable). However `enderDragonNoDestroyBlock` does not get dragon slower. 

### Steps to reproduce

1. Create a world
2. Get into end, see how it go through the floor
3. Enable the feature, compare the different speed

### Minecraft version

Any

### TemplateMod version

newest

### Check list

- [X] I have verified that the issue persists in the latest version of the mod.
- [X] I have searched the existing issues and confirmed that this is not a duplicate.

**Comment by 1024-byteeeee** [comment]
### Changelog
#### https://minecraft-ams.github.io/carpetamsaddition/2024/01/18/v2.27.1/
