### ISSUE TITLE
1.20.1版本 在同时安装此mod和机械动力的时候有夜视效果的时候打开背包会崩溃

### ISSUE THREAD

**Issue by AshdoII** [Minecraft-AMS/Carpet-AMS-Addition#91]
### Bug description

在同时安装此mod和机械动力的时候有夜视效果的时候打开背包会崩溃，移除carpet ams addition或者create任意一个就不会崩溃。怀疑和这个有关。 https://github.com/Fabricators-of-Create/Porting-Lib/issues/75
游戏版本1.20.1 fabric版本0.15.6

### Steps to reproduce

1.同时安装carpet1.4.112 carpet ams addition2.27.1 create0.5.1 fabricapi0.91.0
2.进入世界，给自己一个夜视效果（任意时常）
3.按e打开物品栏，崩溃

### Minecraft version

1.20.1

### TemplateMod version

2.27.1

### Check list

- [X] I have verified that the issue persists in the latest version of the mod.
- [X] I have searched the existing issues and confirmed that this is not a duplicate.

**Comment by 1024-byteeeee** [comment]
会在下个版本得到修复。

**Comment by 1024-byteeeee** [comment]
### Changelog
#### https://minecraft-ams.github.io/carpetamsaddition/2024/01/30/v2.28.0/

**Comment by AshdoII** [comment]
好诶！感谢这么迅速的修复！
