### ISSUE TITLE
游戏启动时崩溃

### ISSUE THREAD

**Issue by snpdzk** [Minecraft-AMS/Carpet-AMS-Addition#95]
### Bug description

将ams地毯升级至2.34.0后，游戏启动时崩溃

### Steps to reproduce

1.启动游戏
2.boom

### Relevant logs

https://pastebin.com/vj1iKDz1

### Minecraft version

1.20.1

### TemplateMod version

2.34.0

### Check list

- [X] I have verified that the issue persists in the latest version of the mod.
- [X] I have searched the existing issues and confirmed that this is not a duplicate.

**Comment by 1024-byteeeee** [comment]
![image](https://github.com/Minecraft-AMS/Carpet-AMS-Addition/assets/77058327/3494ad6b-3b16-438e-8e29-131fd5851f5b)
![image](https://github.com/Minecraft-AMS/Carpet-AMS-Addition/assets/77058327/98188687-2dc8-4fa5-8902-d275ceef9557)
![image](https://github.com/Minecraft-AMS/Carpet-AMS-Addition/assets/77058327/c8a12e8c-2757-47e3-be36-5b166f71bda2)
目前无法复现。

**Comment by JocuperDARY** [comment]
我从2.33升至2.34也会导致这种情况，目前不清楚是与什么mod冲突

**Comment by JocuperDARY** [comment]
删除config文件夹崩溃就解决了

**Comment by 1024-byteeeee** [comment]
> 我从2.33升至2.34也会导致这种情况，目前不清楚是与什么mod冲突

和magiclib冲突

**Comment by 1024-byteeeee** [comment]
待会儿更新，稍等下。

**Comment by 1024-byteeeee** [comment]
@snpdzk @JocuperDARY 

### github
#### https://github.com/Minecraft-AMS/Carpet-AMS-Addition/releases/tag/v2.34.1

---

### Modrinth
#### https://modrinth.com/mod/carpet-ams-addition/versions

试试，我试没问题了。

**Comment by snpdzk** [comment]
没问题了
