### ISSUE TITLE
求加个末影珍珠沿途区块加载的指令

### ISSUE THREAD

**Issue by wj-lxax** [Minecraft-AMS/Carpet-AMS-Addition#96]
用于珍珠炮

**Comment by 1024-byteeeee** [comment]
试试这个？
https://github.com/gnembon/carpet-extra
https://github.com/gnembon/carpet-extra/pull/308

**Comment by wj-lxax** [comment]
> 试试这个？
> https://github.com/gnembon/carpet-extra
> https://github.com/gnembon/carpet-extra/pull/308

我下载了1.20.1最新版，这个并不行，我看到过其他人使用这个mod，也说不行😭😭😭

**Comment by 1024-byteeeee** [comment]
> > 试试这个？
> > https://github.com/gnembon/carpet-extra
> > [gnembon/carpet-extra#308](https://github.com/gnembon/carpet-extra/pull/308)
> 
> 我下载了1.20.1最新版，这个并不行，我看到过其他人使用这个mod，也说不行😭😭😭

那你可以去carpet extra那边详细说说怎么不行，我可能不会添加这个功能，不过我有时间会试试🤔

**Comment by wj-lxax** [comment]
> 说

好的，谢谢

**Comment by Crystal0404** [comment]
> > 试试这个？
> > https://github.com/gnembon/carpet-extra
> > [gnembon/carpet-extra#308](https://github.com/gnembon/carpet-extra/pull/308)
> 
> 我下载了1.20.1最新版，这个并不行，我看到过其他人使用这个mod，也说不行😭😭😭

请尝试https://github.com/Crystal0404/CrystalCarpetAddition

珍珠加载修复的代码是我提交的, 所以你也可以去尝试我的分支https://github.com/Crystal0404/carpet-extra

**Comment by wj-lxax** [comment]
> > > 试试这个？
> > > https://github.com/gnembon/carpet-extra
> > > [gnembon/carpet-extra#308](https://github.com/gnembon/carpet-extra/pull/308)
> > 
> > 我下载了1.20.1最新版，这个并不行，我看到过其他人使用这个mod，也说不行😭😭😭
> 
> 请尝试https://github.com/Crystal0404/CrystalCarpetAddition
> 
> 珍珠加载修复的代码是我提交的, 所以你也可以去尝试我的分支https://github.com/Crystal0404/carpet-extra

好的，谢谢

**Comment by Adogs1** [comment]
现在24w36a添加珍珠可以自加载了
