### ISSUE TITLE
对任意花使用骨粉都可以掉落一个花

### ISSUE THREAD

**Issue by LAGANXIANG** [Minecraft-AMS/Carpet-AMS-Addition#97]
### Motivation

更好的获取花朵

### Description

拿着骨粉对瓶子草，孢子花，火把花还有一些小花，都可以被骨粉催熟一个本体

**Comment by 1024-byteeeee** [comment]
下个版本更新。

**Comment by 1024-byteeeee** [comment]
![image](https://github.com/Minecraft-AMS/Carpet-AMS-Addition/assets/77058327/696f621f-5a1e-4d4c-b2df-a8dee5bdcf60)

**Comment by 1024-byteeeee** [comment]
## Changelog
https://minecraft-ams.github.io/carpetamsaddition/2024/04/03/v2.36.0/

## Github
https://github.com/Minecraft-AMS/Carpet-AMS-Addition/releases/tag/v2.36.0

## Modrinth
https://modrinth.com/mod/carpet-ams-addition/versions

**Comment by 1024-byteeeee** [comment]
> 考虑一下瓶子草和孢子花？

瓶子草是草不是花，下个版本会添加孢子花。

**Comment by 1024-byteeeee** [comment]
https://minecraft-ams.github.io/carpetamsaddition/2024/04/05/v2.37.0/

**Comment by LAGANXIANG** [comment]
希望把瓶子草也加上

1024_byteeeee ***@***.***> 于 2024年4月5日周五 下午6:12写道：

**Comment by LAGANXIANG** [comment]
希望添加一下瓶子草因为他的染料真的很好搞

**Comment by 1024-byteeeee** [comment]
> 希望添加一下瓶子草因为他的染料真的很好搞

我还没体验过高版本，瓶子草原版中有量产方式吗？

**Comment by LAGANXIANG** [comment]
我不管，我就要

**Comment by 1024-byteeeee** [comment]
> 我不管，我就要

我只能单独做一个规则来负责瓶子草了，放现在的可催熟小花里边儿属实感觉不合适🫤

**Comment by cdqtzrc** [comment]
把可催熟小花改成可催熟花草

**Comment by 1024-byteeeee** [comment]
### Changelog
#### https://minecraft-ams.github.io/carpetamsaddition/2024/04/10/v2.38.0/
### GitHub
#### https://github.com/Minecraft-AMS/Carpet-AMS-Addition/releases/tag/v2.38.0
### Modrinth
#### https://modrinth.com/mod/carpet-ams-addition/versions
