### ISSUE TITLE
更好的经验球合并

### ISSUE THREAD

**Issue by cdqtzrc** [Minecraft-AMS/Carpet-AMS-Addition#99]
### Motivation

原版经验球合并有局限性，合并的成功率太低，并且合并后的经验球不能立即被玩家吸收

### Description

![image](https://github.com/Minecraft-AMS/Carpet-AMS-Addition/assets/134773425/8643087d-583f-41c2-8145-98c4a67ea459)

**Comment by 1024-byteeeee** [comment]
用这个就够了。
&emsp;
https://github.com/gnembon/fabric-carpet/wiki/Current-Available-Settings#xpnocooldown
&emsp;
![image](https://github.com/Minecraft-AMS/Carpet-AMS-Addition/assets/77058327/a3a91acd-9abd-485b-ae51-6785f39a720d)
